# Run `conda-env create -f environment.yml`
name: mapclassify
channels:
  - conda-forge

dependencies:
  - python=3.6
  - pip
  - geopandas
  - libpysal
  - ipywidgets
  - jupyter
  - jupyterlab
  - nbconvert
  - palettable
